---
title: "Inference"
output: html_document
---

```{r}
library(ggplot2)
library(ggh4x)
library(sandwich)
#library(lmtest)
library(MASS)
library(dplyr)
#library(rstatix)
#library(lm_robust)
data = read.csv('./Data/results_pt_3.csv')
```

```{r}
data%>%group_by(model,years_between)%>%summarize(auc=mean(auc))%>%ggplot(aes(years_between,auc))+#,color=model))
  geom_point()+geom_line()+#geom_smooth(se=FALSE)+
  facet_wrap(~model,scales = 'free')
  #geom_smooth(method="lm",se=FALSE)

data%>%group_by(model,years_between)%>%summarize(ll=mean(ll))%>%ggplot(aes(years_between,ll))+#,color=model))
  geom_point()+geom_line()+#geom_smooth(se=FALSE)+
  facet_wrap(~model,scales = 'free')

data%>%group_by(model,years_between)%>%summarize(f1=mean(f1))%>%ggplot(aes(years_between,f1))+#,color=model))
  geom_point()+geom_line()+#geom_smooth(se=FALSE)+
  facet_wrap(~model,scales = 'free')
```

```{r}
mods = unique(data['model'])$model
pvals = list()
for (m in mods) {
  sub_df = data[data['model'] == m,]
  print(m)
  test_auc = cor.test(sub_df$years_between,sub_df$auc,method='spearman')
  print(test_auc)
  test_ll = cor.test(sub_df$years_between,sub_df$ll,method='spearman')
  print(test_ll)
  test_f1 = cor.test(sub_df$years_between,sub_df$f1,method='spearman')
  pvals = append(pvals,test_auc$p.value)
  pvals = append(pvals,test_ll$p.value)
  pvals = append(pvals,test_f1$p.value)
}
```

```{r}
p.adjust(pvals,'holm')
```

```{r}
data%>%group_by(model,years_between)%>%summarize(auc_m=mean(auc),auc_low=t.test(auc)$conf.int[1], auc_hi=t.test(auc)$conf.int[2])%>%ggplot(aes(years_between,auc_m))+#,color=model))
  geom_point()+geom_line()+geom_errorbar(aes(ymin=auc_low,ymax=auc_hi,width=.2))+#geom_smooth(se=FALSE)+
  facet_wrap(~model)

t.test(data$auc)$conf.int[2]

int_tib = data%>%group_by(model,years_between)%>%summarize(auc_m=mean(auc),auc_low=t.test(auc)$conf.int[1], auc_hi=t.test(auc)$conf.int[2],ll_m=mean(ll),ll_low=t.test(ll)$conf.int[1],ll_hi=t.test(ll)$conf.int[2],f1_m=mean(f1),f1_low=t.test(f1)$conf.int[1],f1_hi=t.test(f1)$conf.int[2])
```

```{r}
ggplot(int_tib, aes(x=years_between,y=auc_m))+
  geom_point(aes(color=model))+geom_line(aes(color=model))+
  geom_errorbar(aes(ymin=auc_low,ymax=auc_hi,width=.2,color=model))+
  facet_wrap(~model,scales='free')+
  #ggh4x::facet_manual(~model,scales="free",design=a_des)+
  theme(legend.position='none')+
  labs(y='AUC',x='Years between Training & Evaluation Year')

ggplot(int_tib, aes(x=years_between,y=auc_m))+
  geom_point(aes(color=model))+geom_line(aes(color=model))+
  #ggh4x::facet_manual(~model,scales="free",design=a_des)+
  labs(y='AUC',x='Years between Training & Evaluation Year')

ggplot(int_tib, aes(x=years_between,y=ll_m))+
  geom_point(aes(color=model))+geom_line(aes(color=model))+
  geom_errorbar(aes(ymin=ll_low,ymax=ll_hi,width=.2,color=model))+
  facet_wrap(~model,scales='free')+
  #ggh4x::facet_manual(~model,scales="free",design=a_des)+
  theme(legend.position='none')+
  labs(y='Log Loss',x='Years between Training & Evaluation Year')

ggplot(int_tib, aes(x=years_between,y=ll_m))+
  geom_point(aes(color=model))+geom_line(aes(color=model))+
  #ggh4x::facet_manual(~model,scales="free",design=a_des)+
  labs(y='Log Loss',x='Years between Training & Evaluation Year')

ggplot(int_tib, aes(x=years_between,y=f1_m))+
  geom_point(aes(color=model))+geom_line(aes(color=model))+
  geom_errorbar(aes(ymin=f1_low,ymax=f1_hi,width=.2,color=model))+
  facet_wrap(~model,scales='free')+
  #ggh4x::facet_manual(~model,scales="free",design=a_des)+
  theme(legend.position='none')+
  labs(y='F1 Score',x='Years between Training & Evaluation Year')

ggplot(int_tib, aes(x=years_between,y=f1_m))+
  geom_point(aes(color=model))+geom_line(aes(color=model))+
  #ggh4x::facet_manual(~model,scales="free",design=a_des)+
  labs(y='F1 Score',x='Years between Training & Evaluation Year')

#ggsave(plo,filename='./diff_with_error_bars.png',width=4,height=5)
```

```{r}
ggplot(int_tib, aes(x=years_between,y=auc_m))+
  geom_errorbar(aes(ymin=auc_low,ymax=auc_hi,width=.05,color=model))+
  geom_point(aes(color=model))+geom_line(aes(color=model))
```

```{r}
#param_nums = read.csv('./Data/param_numbers.csv')
#param_nums%>%group_by(model)%>%summarize(avg_params=mean(num_trainable_params))
```

```{r}
sakt_e = data[data['model'] == 'SAKT-E',]
sakt_kc = data[data['model'] == 'SAKT-KC',]

cor.test(sakt_e$auc,sakt_kc$auc,method='spearman')

all_sakt = rbind(sakt_e,sakt_kc)

sakt_mod = lm(rank(auc)~years_between*model,data=all_sakt)
summary(sakt_mod)
coeftest(sakt_mod,vcov.=vcovHC)
plot(sakt_mod,which=c(1,3))

pred <- predict(sakt_mod)
ggplot(all_sakt,aes(years_between,auc,color=model))+geom_point(alpha=0.2)+
  geom_line(aes(y=pred))+
  labs(y='AUC',x='Years between Training & Evaluation Year')+
  scale_color_discrete(name="Model")

#ggsave(plo1,filename='./sakt_line.png',width=4,height=3)
  
```

```{r}
bc = boxcox(all_sakt$auc ~ all_sakt$years_between*all_sakt$model, lambda = seq(-10,0,1/20))
bc$x[which.max(bc$y)]
```

```{r}
bc_transform = function(y, ld) {
  if (ld == 0) {
    log(y)
  }
  else {
    ((y^ld) - 1) / ld
  }
}

ggplot(all_sakt, aes(auc,fill=model))+geom_histogram()

ggplot(all_sakt, aes(bc_transform(auc,-4.6),fill=model))+geom_histogram()


sakt_mod = lm(bc_transform(auc, -4.6)~years_between*model,data=all_sakt)
summary(sakt_mod)
coeftest(sakt_mod,vcov.=vcovHC)
plot(sakt_mod,which=c(1,3))

```

```{r}
all_bkt = data[data['model'] == 'BKT',]
res_aov = aov(auc~factor(years_between), data=all_bkt)
summary(res_aov)
TukeyHSD(res_aov)
```

```{r}
data_new <- data %>% mutate (
  bkt_auc = ifelse(model == "BKT", auc, NA),
  pfa_auc = ifelse(model == "PFA", auc, NA),
  dkt_auc = ifelse(model == "DKT", auc, NA),
  sakt_kc_auc = ifelse(model == "SAKT-KC", auc, NA),
  sakt_e_auc = ifelse(model == "SAKT-E", auc, NA)
) %>% 

select (-auc)

data_new
```
